# Generated by Django 5.1.1 on 2024-09-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCare', '0005_equipmenttype_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='equipments',
            field=models.ManyToManyField(related_name='maintenance_request', to='propertyCare.equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='propertyCare.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_request', to='propertyCare.team'),
        ),
    ]
