# Generated by Django 5.1.1 on 2024-09-18 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCare', '0006_maintenancerequest_equipments_alter_equipment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='propertyCare.team'),
        ),
    ]
