# Generated by Django 5.1.1 on 2024-09-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCare', '0007_task_assigned_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_request', to='propertyCare.floor'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_request', to='propertyCare.room'),
        ),
    ]
