# Generated by Django 5.1.1 on 2024-09-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCare', '0008_maintenancerequest_floor_maintenancerequest_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_team',
        ),
    ]
